package id.ac.poliban.mi.nia.listpahlawan;

import java.util.ArrayList;
import java.util.List;

public class DataPahlawan {
    static List<Pahlawan> getPahlawans() {
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("http://4.bp.blogspot.com/-a0KuGx5MaOc/UcOqk8gU8rI/AAAAAAAAAB0/AhrjAHIZY-Q/s1600/Cut+Nyak+Dhien.jpg", "Cut Nyak Dhien (1850-1908)", "Aceh", "Cut Nyak Dhien adalah seorang pahlawan nasional Indonesia yang dilahirkan di Lampadag, Kerajaan Aceh pada tahun 1848. Merupakan salah satu pahlawan wanita yang memiliki semangat perjuangan untuk melawan penjajah Belanda. Cut Nyak Dhien adalah istri seorang pahlawan Indonesia bernama Teuku Umar yang gugur di medan perang tepatnya pada tanggal 11 Januari 1899. Cut Nyak Dhien wafat akibat sakit yang dideritanya dan karena usia. Beliau dimakamkan di Sumedang pada tanggal 6 November tahun 1908."));
            data.add(new Pahlawan("https://1.bp.blogspot.com/-T86C1E4Ke0k/T1dHw9e8RMI/AAAAAAAAAMg/LjaErJWG1i0/s1600/SUKARNO_14.jpg", "Ir. Soekarno (1901-1970)", "Surabaya", "Soekarno atau yang lebih sering disebut Sukarno merupakan presiden pertama di Indonesia. Beliau mendapa sebutan sebagai bapak proklamator kemerdekaan Indonesia yang diselenggarakan pada tanggal 17 Agustus 1945. Sukarno lahir di Surabaya pada tanggal 6 Juni tahun 1901. Dikenal sebagai orator terbaik yang cerdas, Sukarno mampu menciptakan semangat nasional. Selama masa-masa penting Indonesia, Sukarno pernah mencetuskan negara Pancasila, sehingga terciptalah konsep dasar negara bernama Pancasila yang digunakan Indonesia sampai saat ini."));
            data.add(new Pahlawan("https://cdn2.boombastis.com/wp-content/uploads/2016/05/Pangeran-Diponegoro-pecinta-akik.jpg", "Pangeran Diponegoro (1785-1855)", "Yogyakarta", "Pangeran Diponegoro adalah putra pertama dari Raja Mataram, Sultan Hamengkubuwono III. Nama asli Pangeran Diponegoro adalah Mustahar yang lahir di Yogyakarta tepatnya pada tanggal 11 November 1785. Beliau mendapat julukan Pangeran Diponegoro karena telah memimpin perang Diponegoro yang terjadi pada tahun 1825 hingga 1830 antara rakyat Indonesia dengan pemerintah Hindia-Belanda."));
            data.add(new Pahlawan("https://3.bp.blogspot.com/-QL4vwLDNgZ8/V-S3Rmp974I/AAAAAAAAAO8/3adi9b31UOQOtDyV6Aw4OZZfYWqS3mcOwCLcB/s320/tuanku-imam-bonjol-2.jpg", "Tuanku Imam Bonjol (1772-1864)", "Sumatera Barat", "Seorang ulama yang beasal dari Sumatera Barat ini dikenal karena beberapa gelar seperti Peto Syarif dan Malin Basa. Beliau adalah pemimpin perang Padri (1803-1838). Tuanku Imam Bonjol dilahirkan di Bonjol Sumatera Barat pada 1772 yang ditunjuk sebagai pemimpun kaum Padri di kota Bonjol sehingga ia dijuluki Tuanku Imam Bonjol. Semasa perjuangannya, beliau pernah diasingkan hingga wafat lalu dimakamkan di Minahasa pada tanggal 6 November tahun 1864."));
            data.add(new Pahlawan("https://singgalangmasuksekolahh.files.wordpress.com/2011/04/kartini1.jpg", "Raden Adjeng Kartini (1879 - 1904)", "Jawa Tengah", "R.A Kartini beliau dikenal sbg slaah satu pahlawan nasional yang dikenal gigih memeperjuangkan emansipasi wanita kala ia hidup. mengenai Biografi dan Profil R.A Kartini, beliau lahir pada tanggal 21 April 1879 di Kota Jepara, Hari kelahirannya itu kemudian diperingati sebagai Hari Kartini untuk menghormati jasa-jasanya pd Bangsa Indonesia. Kartini lahir di tengah-tengah keluarga bangsawan oleh sebab itu ia memperoleh gelar R.A (Raden Ajeng) di depan namanya, gelar itu sendiri (Raden Ajeng) dipergunakan oleh Kartini sebelum menikah, jika sudah menikah maka gelar kebangsawanan yang dipergunakan R.A (Raden Ayu) menurut tradisi Jawa."));
            data.add(new Pahlawan("https://initu.id/wp-content/uploads/2016/08/playbuzzcom-450x300.jpg", "Pattimura (1783-1817)", "Maluku", "Pattimura atau dikenal dengan Kapitan Pattimura mempunyai nama asli Thomas Matulessy. Kapitan Pattimura lahir di Maluku pada tanggal 8 Juni tahun 1783. Ia dikenal sebagai pemimpin pasukan pada peperangan-peperangan besar salah satunya perang tahun 1817. Pattimura juga mampu menyatukan semangat dari kerajaan Ternate hingga Tidore. Perang yang paling terkenal adalah perang Pattimura yang sangat ganas."));
        }
        return data;
    }
}
